/**
 * Generates Definitions and Logs
 */

/**
 *
 * @author Daikaiser
 */
public class DefGenerator extends javax.swing.JFrame {

    /**
     * Creates new form DefGenerator
     */
    public DefGenerator() {
        initComponents();
    }
    
    public DefGenerator(Expression e){
        this();
        this.setTitle(e.word);
        for(String definition:e.definitions){
            this.txtDefinition.setText(txtDefinition.getText()+"=> "+definition+"\n");
        }
    }
    
    public DefGenerator(Expression[]expressions){
        this();
        this.setTitle("Expressions Data");
        for(Expression expression:expressions){
            this.txtDefinition.setText(txtDefinition.getText()+"====================\n");
            this.txtDefinition.setText(txtDefinition.getText()+"Word:"+expression.word+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"POSTag:"+expression.postag+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"NERTag:"+expression.nertag+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"Word Inappropriateness level:"+expression.value+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"Sentiment Value:"+expression.sentimentValue+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"Structural Inappropriateness:"+expression.isInvoked+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"isInappropriate:"+expression.isInappropriate+"\n");
            this.txtDefinition.setText(txtDefinition.getText()+"Targetable Entity:"+InappExp.targetableUnit(expression)+"\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDefinition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDefinition.setEditable(false);
        txtDefinition.setColumns(20);
        txtDefinition.setRows(5);
        jScrollPane1.setViewportView(txtDefinition);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDefinition;
    // End of variables declaration//GEN-END:variables
}
