/**
 *
 * @author Anj Lasala
 */
public class LogsUI extends javax.swing.JFrame {

    /**
     * Creates new form LogsUI
     */
    public LogsUI() {
        initComponents();
    }
    
    public LogsUI(Report report){
        this();
        this.setVisible(true);
        this.txtPOSTag.setText(report.postag);
        this.txtNERTag.setText(report.nertag);
        for(Expression expression:report.expressions){
            this.txtDefinitions.setText(txtDefinitions.getText()+expression.word+"\n");
            for(String definition:expression.definitions){
                this.txtDefinitions.setText(txtDefinitions.getText()+"=>"+definition+"\n");
            }
            for(String definition:expression.urbanDefinitions){
                this.txtDefinitions.setText(txtDefinitions.getText()+"=>"+definition+"\n");
            }
            this.txtSentiAna.setText(txtSentiAna.getText()+"====================\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"Word:"+expression.word+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"POSTag:"+expression.postag+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"NERTag:"+expression.nertag+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"Word Inappropriateness level:"+expression.value+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"Sentiment Value:"+expression.sentimentValue+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"Structural Inappropriateness:"+expression.isInvoked+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"isInappropriate:"+expression.isInappropriate+"\n");
            this.txtSentiAna.setText(txtSentiAna.getText()+"Targetable Entity:"+InappExp.targetableUnit(expression)+"\n");
        }
        this.txtNGrams.setText(report.ngram);
        this.txtRIA.setText(report.ria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        txtNERTag = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDefinitions = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPOSTag = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSentiAna = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtRIA = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtNGrams = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Logs");

        txtNERTag.setColumns(20);
        txtNERTag.setRows(5);
        jScrollPane3.setViewportView(txtNERTag);
        txtNERTag.getAccessibleContext().setAccessibleName("NERTag");

        txtDefinitions.setColumns(20);
        txtDefinitions.setRows(5);
        jScrollPane4.setViewportView(txtDefinitions);
        txtDefinitions.getAccessibleContext().setAccessibleName("DefinitionExtraction");

        txtPOSTag.setColumns(20);
        txtPOSTag.setRows(5);
        jScrollPane5.setViewportView(txtPOSTag);
        txtPOSTag.getAccessibleContext().setAccessibleName("POSTag");

        txtSentiAna.setColumns(20);
        txtSentiAna.setRows(5);
        jScrollPane6.setViewportView(txtSentiAna);
        txtSentiAna.getAccessibleContext().setAccessibleName("InappExpressScoring");

        txtRIA.setColumns(20);
        txtRIA.setRows(5);
        jScrollPane7.setViewportView(txtRIA);
        txtRIA.getAccessibleContext().setAccessibleName("SentimentScoring");

        txtNGrams.setColumns(20);
        txtNGrams.setRows(5);
        jScrollPane8.setViewportView(txtNGrams);
        txtNGrams.getAccessibleContext().setAccessibleName("NGRAMAnalysis");

        jLabel1.setText("POS Tag");

        jLabel2.setText("NER Tag");

        jLabel3.setText("NGRAM Analysis");

        jLabel4.setText("Definition Extraction");

        jLabel5.setText("InappExpress Scoring");

        jLabel6.setText("Relational Inference Analyzer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel1)
                .addGap(287, 287, 287)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addGap(233, 233, 233)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTextArea txtDefinitions;
    public javax.swing.JTextArea txtNERTag;
    public javax.swing.JTextArea txtNGrams;
    public javax.swing.JTextArea txtPOSTag;
    public javax.swing.JTextArea txtRIA;
    public javax.swing.JTextArea txtSentiAna;
    // End of variables declaration//GEN-END:variables
}
